CREATE TABLE "nauka-ppla_license" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nauka-ppla_license_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"url" varchar(255) NOT NULL,
	"description" text,
	CONSTRAINT "nauka-ppla_license_url_unique" UNIQUE("url")
);
--> statement-breakpoint
ALTER TABLE "nauka-ppla_category" DROP CONSTRAINT "nauka-ppla_category_url_unique";--> statement-breakpoint
ALTER TABLE "nauka-ppla_category" ADD COLUMN "license" integer;--> statement-breakpoint
ALTER TABLE "nauka-ppla_category" ADD CONSTRAINT "nauka-ppla_category_license_nauka-ppla_license_id_fk" FOREIGN KEY ("license") REFERENCES "public"."nauka-ppla_license"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nauka-ppla_category" ADD CONSTRAINT "nauka-ppla_category_url_license_unique" UNIQUE("url","license");