CREATE TYPE "public"."answer" AS ENUM('A', 'B', 'C', 'D');--> statement-breakpoint
CREATE TABLE "nauka-ppla_exam_attempt" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"categoryId" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "nauka-ppla_exam_attempt_userId_categoryId_unique" UNIQUE("userId","categoryId")
);
--> statement-breakpoint
CREATE TABLE "nauka-ppla_exam_questions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nauka-ppla_exam_questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"examAttemptId" varchar(255) NOT NULL,
	"questionInstanceId" varchar(255) NOT NULL,
	"answer" "answer"
);
--> statement-breakpoint
ALTER TABLE "nauka-ppla_exam_attempt" ADD CONSTRAINT "nauka-ppla_exam_attempt_userId_nauka-ppla_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."nauka-ppla_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nauka-ppla_exam_attempt" ADD CONSTRAINT "nauka-ppla_exam_attempt_categoryId_nauka-ppla_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."nauka-ppla_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nauka-ppla_exam_questions" ADD CONSTRAINT "nauka-ppla_exam_questions_examAttemptId_nauka-ppla_exam_attempt_id_fk" FOREIGN KEY ("examAttemptId") REFERENCES "public"."nauka-ppla_exam_attempt"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nauka-ppla_exam_questions" ADD CONSTRAINT "nauka-ppla_exam_questions_questionInstanceId_nauka-ppla_question_instance_id_fk" FOREIGN KEY ("questionInstanceId") REFERENCES "public"."nauka-ppla_question_instance"("id") ON DELETE no action ON UPDATE no action;