import "~/styles/globals.css";
import "katex/dist/katex.min.css";

// import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

import Navbar from "~/app/_components/navbar/navbar";
import { SessionProvider } from "next-auth/react";
import { Notifications } from "./_components/notifications";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="flex min-h-screen flex-col">
        <SessionProvider>
          <TRPCReactProvider>
            <Navbar />
            <main className="container mx-auto flex-1 p-4">{children}</main>
            <Notifications />
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
