INSERT INTO "nauka-ppla_category" ("id", "name", "url", "color") VALUES (1, 'Prawo lotnicze', 'prawo-lotnicze', '#FFCDD2,#EF9A9A');
INSERT INTO "nauka-ppla_category" ("id", "name", "url", "color") VALUES (2, 'Ogólna wiedza o statku powietrznym', 'ogolna-wiedza-o-statku-powietrznym', '#BBDEFB,#90CAF9');
INSERT INTO "nauka-ppla_category" ("id", "name", "url", "color") VALUES (3, 'Osiągi i planowanie lotu', 'osiagi-i-planowanie-lotu', '#C8E6C9,#A5D6A7');
INSERT INTO "nauka-ppla_category" ("id", "name", "url", "color") VALUES (4, 'Człowiek - możliwości i ograniczenia', 'czlowiek-mozliwosci-i-ograniczenia', '#E1BEE7,#CE93D8');
INSERT INTO "nauka-ppla_category" ("id", "name", "url", "color") VALUES (5, 'Meteorologia', 'meteorologia', '#FFE0B2,#FFCC80');
INSERT INTO "nauka-ppla_category" ("id", "name", "url", "color") VALUES (6, 'Nawigacja', 'nawigacja', '#B2DFDB,#80CBC4', '#B2DFDB,#80CBC4');
INSERT INTO "nauka-ppla_category" ("id", "name", "url", "color") VALUES (7, 'Procedury operacyjne', 'procedury-operacyjne', '#C5CAE9,#9FA8DA');
INSERT INTO "nauka-ppla_category" ("id", "name", "url", "color") VALUES (8, 'Zasady lotu', 'zasady-lotu', '#F8BBD0,#F48FB1');
INSERT INTO "nauka-ppla_category" ("id", "name", "url", "color") VALUES (9, 'Łączność', 'lacznosc', '#FFECB3,#FFE082');

UPDATE "nauka-ppla_question" SET category=1 WHERE "externalId" LIKE 'PL010%';
UPDATE "nauka-ppla_question" SET category=1 WHERE "externalId" LIKE 'PL099%';
UPDATE "nauka-ppla_question" SET category=1 WHERE "externalId" LIKE 'PL100%';
UPDATE "nauka-ppla_question" SET category=2 WHERE "externalId" LIKE 'PL020%';
UPDATE "nauka-ppla_question" SET category=3 WHERE "externalId" LIKE 'PL030%';
UPDATE "nauka-ppla_question" SET category=4 WHERE "externalId" LIKE 'PL040%';
UPDATE "nauka-ppla_question" SET category=5 WHERE "externalId" LIKE 'PL050%';
UPDATE "nauka-ppla_question" SET category=6 WHERE "externalId" LIKE 'PL060%';
UPDATE "nauka-ppla_question" SET category=7 WHERE "externalId" LIKE 'PL070%';
UPDATE "nauka-ppla_question" SET category=8 WHERE "externalId" LIKE 'PL080%';
UPDATE "nauka-ppla_question" SET category=9 WHERE "externalId" LIKE 'PL090%';
